### ISSUE TITLE
A small bug in ml-bench/transformer 's compilation?

### ISSUE THREAD

**Issue by ziyuhuang123** [parasailteam/cusync#4]
When I run transformer's compilation, I met two issues:

1. NVCC is not correct, I change "/usr/local/cuda-12.2/bin/nvcc" into "/usr/local/cuda/bin/nvcc", is cuda-12.2 necessary? (Maybe not..?)
2. I need to mannually create a build folder: mkdir -p build. I guess the makefile should add this somewhere...

**Comment by abhijangda** [comment]
Good point. There are instructions on how to use script for evaluation. these instructions will be uploaded in sometime.
